#include<stdio.h>
#include<conio.h>
main()
{
	int a=10,b=20, A=5,B=10, a1=100,b1=200, A1=300,B1=400, A_B=10,a_b=20;
	clrscr();
	printf("\na=%d0",a);
	printf("\nb-%d", b);
	printf("\n\nA=%d",A);
	printf("\nB=%d",B);
	printf("\n\na1=%d",a1);
	printf("\nb1=%d",b1);
	printf("\n\nA1=%d",A1);
	printf("\nB1=%d",B1);
	printf("\n\nA_B=%d",A_B);
	printf("\na_b+=%d",a_b);
	return 0;
}



